### PR TITLE
Initial Integration: Legion with sql2dbx - Add bridge notebook and update job infrastructure

### PR DESCRIPTION
**Pull request by hiroyukinakazato-db**
As an initial integration between Project Legion and sql2dbx, I've made changes to allow Legion to call sql2dbx without modifying sql2dbx itself. We plan to implement advanced integration in the coming weeks. The main changes are as follows:

## Modified to include sql2dbx in uploaded materials
- Added notebooks and scripts to `jobs/sql2dbx`
- Updated `utils/initialsetup.py` to allow specifying folders for upload

## Created job for sql2dbx
- Added `jobs/legion_sql2dbx_runner.py`. This is a bridge notebook between Legion and sql2dbx, which maps Legion's `agent_configs` and `app_configs` to sql2dbx parameters and executes sql2dbx.
- Created a workflow in `infra/jobs_infra.py` that uses `jobs/legion_sql2dbx_runner.py` as a task

### CODE REVIEW

**Review by robertwhiffin — COMMENTED** [review]
@hiroyukinakazato-db have you tested this - does it work as expected?

**Comment by robertwhiffin** [comment]
My main thought with looking at this is our approaches are very similar. I don't see sql2dbx keeping track of the prompt history over time like legion currently does? I'm having second thoughts about this blanket rip and replace approach as we spoken about this more, what about you?

**Comment by nakazax** [comment]
@robertwhiffin This change has been tested and sql2dbx operates without errors from Legion's Batch execution instructions, successfully outputting notebooks.
In this change, I haven't made any modifications to sql2dbx itself. What do you think about merging this with Legion's approach of tracking prompt history chronologically in the next change?

**Comment by hiroyukinakazato-db** [comment]
@robertwhiffin This change has been tested and sql2dbx operates without errors from Legion's Batch execution instructions, successfully outputting notebooks.
In this change, I haven't made any modifications to sql2dbx itself. What do you think about merging this with Legion's approach of tracking prompt history chronologically in the next change?

**Comment by hiroyukinakazato-db** [comment]
As discussed offline, I will close this PR.

**Pull request closed without merging**
